[package]
name = "paste"
version = "0.1.6"
authors = ["David Tolnay <dtolnay@gmail.com>"]
edition = "2018"
license = "MIT OR Apache-2.0"
description = "Macros for all your token pasting needs"
repository = "https://github.com/dtolnay/paste"
readme = "README.md"

[badges]
travis-ci = { repository = "dtolnay/paste" }

[dependencies]
paste-impl = { version = "=0.1.6", path = "impl" }
proc-macro-hack = "0.5"

[workspace]
members = ["impl"]
